import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title> code mesh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      

      <main className={styles.main}>



        <h1 className={styles.title}>
          Welcome to <a href="">codeMesh</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>Codemesh</code>
        </p>

        <div className={styles.grid}>
          <a href="" className={styles.card}>
            <h2>code with python </h2>
            <p>it's very easy to learn </p>
          </a>

          <a href="" className={styles.card}>
            <h2>Code with Java</h2>
            <p>it is very good OOPS programming!</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>HTML and CSS</h2>
            <p>you can very easly can design </p>
          </a>

          <a
            href=""
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Javascript</h2>
            <p>
              it's is the language of web
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
